"""Agrego producto_id a receta

Revision ID: d6c42f0b8bf0
Revises: 0c0953aa67e2
Create Date: 2025-04-03 00:50:52.035520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6c42f0b8bf0'
down_revision = '0c0953aa67e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('ingrediente')
    op.drop_table('galleta')
    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'producto_terminado', ['producto_id'], ['id'])

    with op.batch_alter_table('receta_ingrediente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materia_prima_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('receta_ingrediente_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'materia_prima', ['materia_prima_id'], ['id'])
        batch_op.drop_column('ingrediente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta_ingrediente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingrediente_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('receta_ingrediente_ibfk_2', 'ingrediente', ['ingrediente_id'], ['id'])
        batch_op.drop_column('materia_prima_id')

    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producto_id')

    op.create_table('galleta',
    sa.Column('idGalleta', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('existencias', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio', mysql.FLOAT(), nullable=True),
    sa.Column('gramaje', mysql.FLOAT(), nullable=True),
    sa.Column('vidaAnaquel', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('idGalleta'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingrediente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto',
    sa.Column('idProducto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombreProducto', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fechaCaducidad', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('idProducto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
